version: "3.8"

services:
  postgres:
    container_name: "postgres"
    restart: always 
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      TZ: "Asia/Seoul"
    ports:
      - 5000:5432
  
  django:
    container_name: "django"
    build: . 
    ports:
      - 8888:8000
    environment:
      TZ: "Asia/Seoul"
    volumes:
      -  /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    depends_on:
      - postgres
