version: "3.8"

services:
  postgres:
    container_name: "postgres"
    restart: always 
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: postgres
      TZ: "Asia/Seoul"
      # TZ: "UTC"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5000:5432

  django:
    container_name: "django"
    build: . 
    ports:
      - 8888:8888
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8888 --timeout=300 --capture-output --log-level debug
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      - postgres

  migrate:
    build: .
    command: python manage.py migrate
    depends_on:
      - postgres

 